"""
Django settings for journal_back project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Загружаем переменные из .env файла, который лежит в корне проекта
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2@x#t4x&2b^s80eqh^#-gz^14k@z&k2!)&n$2o)20-tmlzs1*m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['diary.local', 'localhost', '127.0.0.1', '*']

# 👇 ДОБАВЬ ЭТОТ БЛОК СРАЗУ ПОД ALLOWED_HOSTS 👇
CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://diary.local:8000',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'tinymce',
    'trades',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'journal_back.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'journal_back.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'quantum_db',           # Имя базы, которую мы создали
        'USER': 'postgres',             # Стандартный логин Postgres
        'PASSWORD': '123',      # 👈 ВПИШИ СЮДА ПАРОЛЬ ОТ СВОЕГО POSTGRESQL
        'HOST': '127.0.0.1',            # База крутится локально
        'PORT': '5432',                 # Стандартный порт Postgres
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Разрешаем всем стучаться (для тестов на локалке)
CORS_ALLOW_ALL_ORIGINS = True
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- АВТОРИЗАЦИЯ И СЕССИИ ---
LOGIN_REDIRECT_URL = '/api/trades/'
LOGOUT_REDIRECT_URL = '/api-auth/login/'
LOGIN_URL = '/api-auth/login/'

# Удерживаем сессию 30 дней
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 2592000

SESSION_COOKIE_NAME = 'diary_sessionid'
CSRF_COOKIE_NAME = 'diary_csrftoken'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'trades.authentication.CsrfExemptSessionAuthentication',  # 👈 Изменили путь здесь
        'rest_framework.authentication.BasicAuthentication',
    ),
}

# --- НАСТРОЙКИ ВИЗУАЛЬНОГО РЕДАКТОРА TINYMCE ---
TINYMCE_DEFAULT_CONFIG = {
    'height': 500,
    'promotion': False,
    'license_key': 'gpl',
    'menubar': True,
    # Принудительно включаем темную тему, чтобы не слепило глаза в админке
    'skin': 'oxide-dark',
    'content_css': 'dark',

    # Твои плагины
    'plugins': 'advlist autolink lists link image charmap preview anchor searchreplace visualblocks code fullscreen insertdatetime table help wordcount codesample',

    # Твоя панель инструментов (много кнопок)
    'toolbar': 'undo redo | blocks | bold italic forecolor | codesample | alignleft aligncenter alignright alignjustify | bullist numlist checklist outdent indent | table link image | removeformat | fullscreen',

    # Подсветка синтаксиса кода
    'codesample_languages': [
        {'text': 'HTML/XML', 'value': 'markup'},
        {'text': 'JavaScript', 'value': 'javascript'},
        {'text': 'JSON', 'value': 'json'},
        {'text': 'CSS', 'value': 'css'},
        {'text': 'Python', 'value': 'python'},
        {'text': 'C++', 'value': 'cpp'}
    ],

    'image_title': True,
    'automatic_uploads': True,
    'file_picker_types': 'image',

    # Разрешает вставлять скриншоты из буфера обмена (Ctrl+V)
    # и автоматически конвертирует их в base64 прямо в HTML-код!
    'paste_data_images': True,

    'table_default_attributes': {
        'border': '1'
    },
    'table_default_styles': {
        'width': '100%',
        'border-collapse': 'collapse'
    },
    'verify_html': False,
}


TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")