# Generated by Django 6.0.3 on 2026-03-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.BigIntegerField(unique=True)),
                ('symbol', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('volume', models.FloatField()),
                ('entry_price', models.FloatField()),
                ('profit', models.FloatField()),
                ('time', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('strategy_name', models.CharField(default='ICT', max_length=50)),
            ],
        ),
    ]
