# Generated by Django 6.0.3 on 2026-03-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='screenshot_entry',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/entry/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='trade',
            name='screenshot_exit',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/exit/%Y/%m/%d/'),
        ),
    ]
