# Generated by Django 6.0.3 on 2026-03-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_trade_screenshot_entry_trade_screenshot_exit'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='timeframe',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
