# Generated by Django 6.0.3 on 2026-03-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_trade_timeframe'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaybookPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('setup_name', models.CharField(max_length=50)),
                ('timeframe', models.CharField(max_length=10)),
                ('ideal_screenshot', models.ImageField(upload_to='playbook/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
