# Generated by Django 6.0.3 on 2026-03-04 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_playbookpattern_user_trade_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='psychology',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='playbookpattern',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playbookpattern',
            name='setup_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='playbookpattern',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='playbookpattern',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trade',
            name='screenshot_entry',
            field=models.ImageField(blank=True, null=True, upload_to='trades/'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='screenshot_exit',
            field=models.ImageField(blank=True, null=True, upload_to='trades/'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='strategy_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='ticket',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trade',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
