# Generated by Django 6.0.3 on 2026-03-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_trade_is_processed_trade_psychology_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='confluence_factors',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='setup_grade',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
