# Generated by Django 6.0.3 on 2026-03-05 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_trade_confluence_factors_trade_setup_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(default=1)),
                ('timeframe', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='trades/reviews/')),
                ('mentor_comment', models.TextField(verbose_name='Что сказал RS')),
                ('error_type', models.CharField(blank=True, choices=[('BIAS_ERROR', 'Против контекста HTF'), ('FAKE_BOS', 'Фейк-слом'), ('RANGE_MIDDLE', 'Вход в середине боковика'), ('LIQUIDITY_GAP', 'Игнор ликвидности'), ('EARLY_ENTRY', 'Спешка (не дождался закрытия)'), ('LOGIC_FAIL', 'Галлюцинация / Пиво')], max_length=20, null=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_reviews', to='trades.trade')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='TradeScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='trades/analysis/')),
                ('description', models.TextField(blank=True, null=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_screens', to='trades.trade')),
            ],
        ),
    ]
