# Generated by Django 6.0.3 on 2026-03-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0008_reviewstep_tradescreenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='entry_logic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='market_trend',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
