# Generated by Django 6.0.3 on 2026-03-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0009_trade_entry_logic_trade_market_trend'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='auto_screen_h1',
            field=models.ImageField(blank=True, null=True, upload_to='trades/auto/'),
        ),
        migrations.AddField(
            model_name='trade',
            name='auto_screen_m1',
            field=models.ImageField(blank=True, null=True, upload_to='trades/auto/'),
        ),
        migrations.AddField(
            model_name='trade',
            name='auto_screen_m15',
            field=models.ImageField(blank=True, null=True, upload_to='trades/auto/'),
        ),
        migrations.AddField(
            model_name='trade',
            name='auto_screen_m5',
            field=models.ImageField(blank=True, null=True, upload_to='trades/auto/'),
        ),
    ]
