# Generated by Django 6.0.3 on 2026-03-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0010_trade_auto_screen_h1_trade_auto_screen_m1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='auto_screen_d1',
            field=models.ImageField(blank=True, null=True, upload_to='trades/auto/'),
        ),
        migrations.AddField(
            model_name='trade',
            name='auto_screen_h4',
            field=models.ImageField(blank=True, null=True, upload_to='trades/auto/'),
        ),
    ]
