# Generated by Django 6.0.3 on 2026-03-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0011_trade_auto_screen_d1_trade_auto_screen_h4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playbookpattern',
            name='setup_name',
        ),
        migrations.RemoveField(
            model_name='playbookpattern',
            name='timeframe',
        ),
        migrations.AddField(
            model_name='playbookpattern',
            name='entry_logic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='playbookpattern',
            name='market_trend',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
