# Generated by Django 6.0.3 on 2026-03-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0013_tradingrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='magic_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Magic Number'),
        ),
        migrations.AddField(
            model_name='trade',
            name='mt5_comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MT5 Комментарий'),
        ),
    ]
