# Generated by Django 6.0.3 on 2026-03-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0015_faqtopic_faqblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingrule',
            name='category',
            field=models.CharField(choices=[('mantra', '📜 Мантра'), ('rule', '💎 Золотое правило'), ('warning', '⚠️ Признак тильта'), ('rev_entry', '🔄 Вход: Разворот'), ('trend_entry', '✅ Вход: По тренду'), ('psy_base', '🛑 Психология и База')], default='rule', max_length=20, verbose_name='Категория'),
        ),
    ]
