# Generated by Django 6.0.3 on 2026-04-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0016_alter_tradingrule_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
