# Generated by Django 6.0.3 on 2026-04-04 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0018_question_quiz_answerchoice_question_quiz_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBacktest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата бэктеста')),
                ('yesterday_close', models.TextField(blank=True, null=True, verbose_name='Вчерашнее закрытие')),
                ('today_plan', models.TextField(blank=True, null=True, verbose_name='План на сегодня')),
                ('grid_data', models.JSONField(default=dict, verbose_name='Матрица ТФ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
