# Generated by Django 6.0.3 on 2026-04-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0019_dailybacktest'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybacktest',
            name='chart_image',
            field=models.ImageField(blank=True, null=True, upload_to='backtest_screens/'),
        ),
    ]
