# Generated by Django 6.0.3 on 2026-04-16 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0021_alter_tradingrule_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqblock',
            options={'ordering': ['created_at']},
        ),
    ]
