# Generated by Django 6.0.3 on 2026-05-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0022_alter_faqblock_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradescreenshot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trades/analysis/'),
        ),
    ]
