# Generated by Django 6.0.6 on 2026-07-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0024_tradeaccount_trade_account_tradeauthor_trade_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Резюме к сделке'),
        ),
    ]
