# Generated by Django 6.0.6 on 2026-09-11 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0025_trade_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='trades.catalogcategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория каталога',
                'verbose_name_plural': 'Категории каталога',
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название ресурса')),
                ('type', models.CharField(choices=[('Indicator', 'Индикатор'), ('Expert', 'Эксперт'), ('Script', 'Скрипт'), ('Utility', 'Утилита (Python)'), ('Book', 'Книга')], max_length=50, verbose_name='Тип')),
                ('default_target_path', models.CharField(blank=True, help_text='Например: \\MQL5\\Indicators\\MyCustom\\', max_length=500, null=True, verbose_name='Стандартный путь на ПК')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trades.catalogcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Ресурс каталога',
                'verbose_name_plural': 'Ресурсы каталога',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Например: v2.1', max_length=50, verbose_name='Версия')),
                ('file', models.FileField(upload_to='catalog/', verbose_name='Файл')),
                ('release_notes', models.TextField(blank=True, null=True, verbose_name='Описание изменений')),
                ('input_parameters', models.TextField(blank=True, null=True, verbose_name='Входящие параметры')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='trades.catalogitem', verbose_name='Ресурс')),
            ],
            options={
                'verbose_name': 'Версия ресурса',
                'verbose_name_plural': 'Версии ресурсов',
                'ordering': ['-upload_date'],
            },
        ),
    ]
