# Generated by Django 6.0.6 on 2026-09-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0026_catalogcategory_catalogitem_itemversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Общее описание (что делает)'),
        ),
        migrations.AddField(
            model_name='itemversion',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/screens/', verbose_name='Скриншот графика'),
        ),
        migrations.AddField(
            model_name='itemversion',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='catalog/sources/', verbose_name='Исходный код (.mq5, .py)'),
        ),
        migrations.AlterField(
            model_name='itemversion',
            name='file',
            field=models.FileField(upload_to='catalog/compiled/', verbose_name='Исполняемый файл (.ex5)'),
        ),
        migrations.AlterField(
            model_name='itemversion',
            name='release_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Описание изменений (Что добавлено)'),
        ),
    ]
